apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: dev
  labels:
    app.kubernetes.io/name: webhook-receiver
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: noc-observability-pipeline
    environment: dev
data:
  PG_HOST: "host.docker.internal"
  PG_PORT: "5432"
  PG_DB: "noc"
  PG_USER: "noc_user"
