apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-ingress
  namespace: dev
  labels:
    app.kubernetes.io/name: webhook-receiver
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: noc-observability-pipeline
    environment: dev
spec:
  ingressClassName: nginx
  rules:
    - host: webhook.local
      http:
        paths:
          - path: /health
            pathType: Exact                 # healthcheck: solo esta ruta exacta
            backend:
              service:
                name: webhook-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhook-service
                port:
                  number: 8000
          
