apiVersion: 1

muteTimes:
  - orgId: 1
    name: maintenance-window-tuesday
    time_intervals:
      - times:
          - start_time: '14:50'
            end_time: '15:10'
        weekdays: ['tuesday']
        location: 'America/Santiago'