apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: default
  labels:
    app: webhook-service
data:
  PG_HOST: "host.docker.internal"
  PG_PORT: "5432"
  PG_DB: "noc"
  PG_USER: "noc_user"
